apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cert-operator
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: cert-operator
    template:
      metadata:
        labels:
          name: cert-operator
      spec:
        containers:
          - name: cert-operator
            image: cert-operator:latest
            ports:
            - containerPort: 60000
              name: metrics
            command:
            - /opt/app-root/cert-operator
            imagePullPolicy: Always
            env:
              - name: WATCH_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: OPERATOR_NAME
                value: "cert-operator"
              - name: CERT_OP_CONFIG
                value: "/etc/cert-operator/config.yml"
            volumeMounts:
              - name: config-volume
                mountPath: /etc/cert-operator
        volumes:
          - name: config-volume
            configMap:
              name: cert-operator-config
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: cert-operator-config
  data:
    config.yml: |
      provider:
        kind: none
