---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-operator
roleRef:
  name: cert-operator-role
subjects:
- kind: ServiceAccount
  name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-operator-cluster-admin
roleRef:
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
