apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-operator-role
rules:
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - services
    - routes
    verbs:
    - create
